export class StorageKeys {
  static readonly APP_KEY = "app_key";
  static readonly USER_INFO_KEY = "user_info_key";
  static readonly USER_LOGIN = "user_login";
  //preference以及AppStorage中token信息 的key
  static readonly TOKEN_INFO_KEY = "TOKEN_INFO_KEY";
  //preference中登录成功的用户名
  static readonly ACCOUNT_KEY = "ACCOUNT_KEY";
  //屏幕的宽高，存在appStorage中。
  static readonly SCREEN_WIDTH = "SCREEN_WIDTH";
  static readonly SCREEN_HEIGHT = "SCREEN_HEIGHT";
}